collections:
  - name: 'pages'
    label: 'Páginas'
    folder: 'src/content/pages'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string', required: false }
      - *pageSettings
      - *pageTheme
      - *mapBox
      - label: 'Componentes'
        name: 'components'
        widget: 'list'
        required: false
        collapsed: true
        types:
          - *group
          - *cta
          - *map
          - *spacer
