column: &column
  label: 'Column'
  name: 'Column'
  widget: 'object'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Column'
      collapsed: true
    - label: 'Padding Top'
      name: paddingTop
      widget: boolean
      default: false
      collapsed: true
    - label: 'Padding Bottom'
      name: paddingBottom
      widget: boolean
      default: false
      collapsed: true
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      collapsed: true
      types:
        - *text
        - *chartBar
        - *chartPercentage
        - *imageBlock
        - *htmlEmbed
        - *videoEmbed
        - *logosGroup
        - *cardsCall
        - *compare
        - *pullquote
        - *spacer
        - *gallery
        - *slider
        - *cards
        - *bigNumbers
        - *button
        - *timeline
        - *innerColumns
