group: &group
  label: 'Group'
  name: 'Group'
  widget: 'object'
  summary: '{{fields.id}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Group'
      collapsed: true
    - label: 'ID'
      name: 'id'
      widget: 'string'
      required: true
      collapsed: true
    - label: 'Layout'
      name: 'layout'
      widget: 'select'
      options: ['default']
      default: 'default'
      collapsed: true
    - label: 'Text Color'
      name: 'txtColor'
      widget: 'color'
      required: false
      enableAlpha: true
      allowInput: true
      collapsed: true
    - label: 'Background Color'
      name: 'bgColor'
      widget: 'color'
      required: false
      enableAlpha: true
      allowInput: true
      collapsed: true
    - label: 'Add Background media'
      name: 'backgroundMedia'
      required: false
      widget: 'list'
      max: 1
      collapsed: true
      types:
        - label: 'Image'
          name: 'backgroundImage'
          widget: 'object'
          collapsed: true
          fields:
            - label: 'Image'
              name: 'imgSrc'
              widget: 'image'
              required: false
              allow_multiple: false
              collapsed: true
        - label: 'Video'
          name: 'backgroundVideo'
          widget: 'object'
          collapsed: true
          fields:
            - label: 'Video'
              name: 'videoSrc'
              widget: 'file'
              allow_multiple: false
              required: false
              collapsed: true
    - label: 'Overlay'
      name: 'overlay'
      widget: 'select'
      options: ['dark', 'light']
      required: false
      collapsed: true
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      collapsed: true
      types:
        - *text
        - *videoEmbed
        - *imageBlock
        - *columnSticky
        - *chartBar
        - *chartPercentage
        - *card
        - *cardsCall
        - *logosGroup
        - *column
        - *columns
        - *timeline
        - *spacer
        - *compare
        - *gallery
        - *slider
