group: &group
  label: 'Group'
  name: 'Group'
  widget: 'object'
  summary: '{{fields.shortTitle}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Group'
      collapsed: true
    - label: 'ID'
      name: 'id'
      widget: 'string'
      required: true
      collapsed: true
    - label: 'Short Title'
      name: 'shortTitle'
      widget: 'string'
      required: true
      hint: 'Título curto (obrigatório) - será usado no futuro'
      collapsed: true
    - label: 'Long Title'
      name: 'longTitle'
      widget: 'string'
      required: false
      hint: 'Título longo usado como label no menu (opcional)'
      collapsed: true
    - label: 'Description'
      name: 'description'
      widget: 'text'
      required: false
      hint: 'Descrição do grupo (opcional) - será usado no futuro'
      collapsed: true
    - label: 'Show in Menu'
      name: 'showInMenu'
      widget: 'boolean'
      default: false
      hint: 'Ativar para mostrar este grupo no menu de navegação'
      collapsed: true
    - label: 'Animations'
      name: 'animations'
      widget: 'boolean'
      default: true
      required: true
      hint: 'Enable/disable animations for this component'
      collapsed: true
    - label: 'Text Color'
      name: 'txtColor'
      widget: 'select'
      options:
        - { label: 'Primary', value: 'Primary' }
        - { label: 'Secondary', value: 'Secondary' }
        - { label: 'Highlight', value: 'Highlight' }
        - { label: 'Custom', value: 'Custom' }
      default: 'Primary'
      required: false
      collapsed: true
    - label: 'Custom Text Color'
      name: 'customTxtColor'
      widget: 'color'
      required: false
      enableAlpha: true
      allowInput: true
      collapsed: true
    - label: 'Background Color'
      name: 'bgColor'
      widget: 'select'
      options:
        - { label: 'Primary', value: 'Primary' }
        - { label: 'Secondary', value: 'Secondary' }
        - { label: 'Highlight', value: 'Highlight' }
        - { label: 'Custom', value: 'Custom' }
      default: 'Secundary'
      required: false
      collapsed: true
    - label: 'Custom Background Color'
      name: 'customBgColor'
      widget: 'color'
      required: false
      enableAlpha: true
      allowInput: true
      collapsed: true
    - label: 'Add Background media'
      name: 'backgroundMedia'
      required: false
      widget: 'list'
      max: 1
      collapsed: true
      types:
        - label: 'Image'
          name: 'backgroundImage'
          widget: 'object'
          collapsed: true
          fields:
            - label: 'Image'
              name: 'imgSrc'
              widget: 'image'
              required: false
              allow_multiple: false
              collapsed: true
        - label: 'Video'
          name: 'backgroundVideo'
          widget: 'object'
          collapsed: true
          fields:
            - label: 'Video'
              name: 'videoSrc'
              widget: 'file'
              allow_multiple: false
              required: false
              collapsed: true
    - label: 'Overlay'
      name: 'overlay'
      widget: 'select'
      options: ['dark', 'light']
      required: false
      collapsed: true
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      collapsed: true
      types:
        - *text
        - *htmlEmbed
        - *videoEmbed
        - *imageBlock
        - *columnSticky
        - *chartBar
        - *chartPercentage
        - *cards
        - *cardsCall
        - *logosGroup
        - *column
        - *columns
        - *timeline
        - *spacer
        - *compare
        - *gallery
        - *slider
