innerColumns: &innerColumns
  label: 'Inner Columns'
  name: 'InnerColumns'
  widget: 'object'
  summary: 'Inner Columns'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'InnerColumns'
      collapsed: true
    - label: 'Column 1'
      name: 'column1'
      widget: 'object'
      required: true
      collapsed: true
      default: null
      fields:
        - label: 'Components'
          name: 'components'
          widget: 'list'
          required: false
          collapsed: true
          types:
            - *text
            - *chartBar
            - *chartPercentage
            - *imageBlock
            - *videoEmbed
            - *logosGroup
            - *bigNumbers
            - *pullquote
            - *spacer
            - *gallery
            - *slider
    - label: 'Column 2'
      name: 'column2'
      widget: 'object'
      required: true
      collapsed: false
      default: null
      fields:
        - label: 'Components'
          name: 'components'
          widget: 'list'
          required: false
          collapsed: true
          types:
            - *text
            - *chartBar
            - *chartPercentage
            - *imageBlock
            - *htmlEmbed
            - *videoEmbed
            - *logosGroup
            - *bigNumbers
            - *pullquote
            - *spacer
            - *gallery
            - *slider
