map: &map
  label: 'Map'
  name: 'Map'
  widget: 'object'
  summary: '{{fields.shortTitle}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Map'
      collapsed: true
    - label: 'ID'
      name: 'id'
      widget: 'string'
      required: true
      collapsed: true
    - label: 'Short Title'
      name: 'shortTitle'
      widget: 'string'
      required: true
      hint: 'Título curto (obrigatório) - será usado no futuro'
      collapsed: true
    - label: 'Long Title'
      name: 'longTitle'
      widget: 'string'
      required: false
      hint: 'Título longo usado como label no menu (opcional)'
      collapsed: true
    - label: 'Description'
      name: 'description'
      widget: 'text'
      required: false
      hint: 'Descrição do componente (opcional) - será usado no futuro'
      collapsed: true
    - label: 'Show in Menu'
      name: 'showInMenu'
      widget: 'boolean'
      default: false
      hint: 'Ativar para mostrar este componente no menu de navegação'
      collapsed: true
    - label: 'Animations'
      name: 'animations'
      widget: 'boolean'
      default: true
      required: true
      hint: 'Enable/disable animations for this component'
      collapsed: true
    - label: 'Column Align'
      name: 'columnAlign'
      widget: 'select'
      options: ['left', 'right', 'center']
      default: 'left'
      required: true
      collapsed: true
    - label: 'Floating Text'
      name: 'floatingText'
      widget: 'boolean'
      required: false
      default: false
      collapsed: true
    - label: 'Text Color'
      name: 'txtColor'
      widget: 'select'
      options:
        - { label: 'Primary', value: 'Primary' }
        - { label: 'Secondary', value: 'Secondary' }
        - { label: 'Highlight', value: 'Highlight' }
      default: 'Primary'
      required: false
      collapsed: true
    - label: 'Background Color'
      name: 'bgColor'
      widget: 'select'
      options:
        - { label: 'Primary', value: 'Primary' }
        - { label: 'Secondary', value: 'Secondary' }
        - { label: 'Highlight', value: 'Highlight' }
      default: 'Secundary'
      required: false
      collapsed: true
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      collapsed: true
      types:
        - *text
        - *spacer
        - *mapView
        - *imageBlock
        - *videoEmbed
        - *timeline
