mapBox: &mapBox
  label: 'MapBox'
  name: 'mapbox'
  collapsed: true
  widget: 'object'
  summary: '{{fields.style}}'
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'MapBox'
    - label: 'Map Style'
      name: 'style'
      widget: 'string'
      required: true
      hint: 'URL do estilo do MapBox (ex: mapbox://styles/username/style-id)'
    - label: 'Map Token'
      name: 'token'
      widget: 'string'
      required: true
      hint: 'Token de acesso do MapBox'
    - label: 'Map Center Longitude'
      name: 'centerLng'
      widget: 'string'
      collapsed: true
      hint: 'Ex: -54.875'
      required: true
    - label: 'Map Center Latitude'
      name: 'centerLat'
      widget: 'string'
      collapsed: true
      hint: 'Ex: -2.53'
      required: true
    - label: 'Map Zoom'
      name: 'zoom'
      widget: 'string'
      default: '2'
      collapsed: true
      hint: 'Valor numérico como string. Ex: 2 ou 2.5'
      required: true
    - label: 'Map Bearing'
      name: 'bearing'
      widget: 'string'
      default: '0'
      collapsed: true
      hint: 'Valor numérico como string. Ex: 0 ou 45.5'
      required: false
    - label: 'Map Pitch'
      name: 'pitch'
      widget: 'string'
      default: '0'
      collapsed: true
      hint: 'Valor numérico como string. Ex: 0 ou 30'
      required: false
    - label: 'Map Layers'
      name: 'layers'
      widget: 'text'
      required: false
      collapsed: true
      hint: 'Uma layer por linha. Formato: "layerName" ou "layerName[property==value]". Ex: mineracao ou mineracao[pais==Brasil]'
    - label: 'Column Align'
      name: 'columnAlign'
      widget: 'select'
      options: ['left', 'center', 'right']
      required: false
      default: 'left'
    - label: 'Floating Text'
      name: 'floatingText'
      widget: 'boolean'
      required: false
      default: false
    - label: 'Map Views'
      name: 'views'
      widget: 'list'
      collapsed: true
      required: false
      fields:
        - label: 'View ID'
          name: 'id'
          widget: 'string'
          required: true
          hint: 'Identificador único da view'
        - label: 'View Center Longitude'
          name: 'centerLng'
          widget: 'string'
          collapsed: true
          hint: 'Ex: -54.875'
          required: true
        - label: 'View Center Latitude'
          name: 'centerLat'
          widget: 'string'
          collapsed: true
          hint: 'Ex: -2.53'
          required: true
        - label: 'View Zoom'
          name: 'zoom'
          widget: 'string'
          collapsed: true
          hint: 'Valor numérico como string. Ex: 8 ou 8.5'
          required: true
        - label: 'Duration (ms)'
          name: 'duration'
          widget: 'string'
          default: '2000'
          collapsed: true
          hint: 'Duração em milissegundos como string. Ex: 2000'
          required: false
        - label: 'View Bearing'
          name: 'bearing'
          widget: 'string'
          default: '0'
          collapsed: true
          hint: 'Valor numérico como string. Ex: 0 ou 45'
          required: false
        - label: 'View Pitch'
          name: 'pitch'
          widget: 'string'
          default: '0'
          collapsed: true
          hint: 'Valor numérico como string. Ex: 0 ou 30'
          required: false
        - label: 'View Layers'
          name: 'layers'
          widget: 'text'
          required: false
          collapsed: true
          hint: 'Uma layer por linha. Ex: mineracao ou mineracao[pais==Brasil]'
        - label: 'Mobile Settings'
          name: 'mobile'
          widget: 'object'
          collapsed: true
          required: false
          fields:
            - label: 'Mobile Zoom'
              name: 'zoom'
              widget: 'string'
              collapsed: true
              required: false
              hint: 'Zoom específico para mobile como string. Ex: 3.5'
        - label: 'Captions'
          name: 'captions'
          widget: 'object'
          collapsed: true
          required: false
          summary: '{{fields.title}}'
          fields:
            - label: 'Title'
              name: 'title'
              widget: 'string'
              required: false
            - label: 'Notes'
              name: 'notes'
              widget: 'text'
              required: false
            - label: 'Legend Items'
              name: 'items'
              widget: 'list'
              collapsed: true
              required: false
              summary: '{{fields.text}}'
              fields:
                - label: 'Icon HTML'
                  name: 'icon'
                  widget: 'text'
                  required: false
                  hint: 'HTML do ícone (ex: <span style="color:red">●</span>)'
                - label: 'Text'
                  name: 'text'
                  widget: 'string'
                  required: false
