mapBox: &mapBox
  label: 'MapBox'
  name: 'mapbox'
  collapsed: true
  widget: 'object'
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'MapBox'
      collapsed: true
    - label: 'Column Align'
      name: 'columnAlign'
      widget: 'select'
      options: ['left', 'center', 'right']
      required: false
      collapsed: true
    - label: 'Floating Text'
      name: 'floatingText'
      widget: 'boolean'
      required: false
      collapsed: true
    - label: 'Map Style'
      name: 'style'
      widget: 'string'
      required: true
      collapsed: true
    - label: 'Map Center'
      name: 'center'
      widget: 'object'
      fields:
        - { label: 'Longitude', name: 'lng', widget: 'number', value_type: 'float', step: 0.01, collapsed: true }
        - { label: 'Latitude', name: 'lat', widget: 'number', value_type: 'float', step: 0.01, collapsed: true }
      required: true
      collapsed: true
    - label: 'Map Zoom'
      name: 'zoom'
      widget: 'number'
      value_type: 'float'
      step: 0.01
      required: true
      collapsed: true
    - label: 'Map Bearing'
      name: 'bearing'
      widget: 'number'
      value_type: 'float'
      step: 0.01
      required: false
      collapsed: true
    - label: 'Map Pitch'
      name: 'pitch'
      widget: 'number'
      value_type: 'float'
      step: 0.01
      required: false
      collapsed: true
    - label: 'Map Layers'
      name: 'layers'
      widget: 'list'
      required: false
      collapsed: true
      fields:
        - label: 'Layer Name'
          name: 'name'
          widget: 'string'
          required: true
          hint: 'Nome da layer no MapBox'
          collapsed: true
        - label: 'Filter Key'
          name: 'filterKey'
          widget: 'string'
          required: false
          hint: 'Propriedade da layer para filtrar (opcional)'
          collapsed: true
        - label: 'Comparison'
          name: 'comparison'
          widget: 'select'
          required: false
          hint: 'Tipo de comparação para o filtro'
          collapsed: true
          options:
            - { label: 'Igual (==)', value: '==' }
            - { label: 'Diferente (!=)', value: '!=' }
            - { label: 'Menor que (<)', value: '<' }
            - { label: 'Maior que (>)', value: '>' }
            - { label: 'Menor ou igual (<=)', value: '<=' }
            - { label: 'Maior ou igual (>=)', value: '>=' }
            - { label: 'Contém (in)', value: 'in' }
            - { label: 'Não contém (!in)', value: '!in' }
            - { label: 'Tem propriedade (has)', value: 'has' }
            - { label: 'Não tem propriedade (!has)', value: '!has' }
        - label: 'Filter Value'
          name: 'filterValue'
          widget: 'string'
          required: false
          hint: 'Valor para comparação (opcional)'
          collapsed: true
    - label: 'Map Token'
      name: 'token'
      widget: 'string'
      required: true
      collapsed: true
    - label: 'Map Views'
      name: 'views'
      widget: 'list'
      required: false
      collapsed: true
      fields:
        - label: 'View ID'
          name: 'id'
          widget: 'string'
          required: true
          collapsed: true
        - label: 'View Center'
          name: 'center'
          widget: 'object'
          fields:
            - { label: 'Longitude', name: 'lng', widget: 'number', collapsed: true }
            - { label: 'Latitude', name: 'lat', widget: 'number', collapsed: true }
          required: true
          collapsed: true
        - label: 'View Duration'
          name: 'duration'
          widget: 'number'
          value_type: 'float'
          step: 0.01
          required: true
          collapsed: true
        - label: 'View Zoom'
          name: 'zoom'
          widget: 'number'
          value_type: 'float'
          step: 0.01
          required: true
          collapsed: true
        - label: 'View Bearing'
          name: 'bearing'
          widget: 'number'
          value_type: 'float'
          step: 0.01
          required: false
          collapsed: true
        - label: 'View Pitch'
          name: 'pitch'
          widget: 'number'
          value_type: 'float'
          step: 0.01
          required: false
          collapsed: true
        - label: 'View Layers'
          name: 'layers'
          widget: 'list'
          required: false
          collapsed: true
          fields:
            - label: 'Layer Name'
              name: 'name'
              widget: 'string'
              required: true
              hint: 'Nome da layer no MapBox'
              collapsed: true
            - label: 'Filter Key'
              name: 'filterKey'
              widget: 'string'
              required: false
              hint: 'Propriedade da layer para filtrar (opcional)'
              collapsed: true
            - label: 'Comparison'
              name: 'comparison'
              widget: 'select'
              required: false
              hint: 'Tipo de comparação para o filtro'
              collapsed: true
              options:
                - { label: 'Igual (==)', value: '==' }
                - { label: 'Diferente (!=)', value: '!=' }
                - { label: 'Menor que (<)', value: '<' }
                - { label: 'Maior que (>)', value: '>' }
                - { label: 'Menor ou igual (<=)', value: '<=' }
                - { label: 'Maior ou igual (>=)', value: '>=' }
                - { label: 'Contém (in)', value: 'in' }
                - { label: 'Não contém (!in)', value: '!in' }
                - { label: 'Tem propriedade (has)', value: 'has' }
                - { label: 'Não tem propriedade (!has)', value: '!has' }
            - label: 'Filter Value'
              name: 'filterValue'
              widget: 'string'
              required: false
              hint: 'Valor para comparação (opcional)'
              collapsed: true
        - label: 'Mobile View'
          name: 'mobile'
          widget: 'object'
          required: false
          collapsed: true
          default: null
          fields:
            - label: 'Mobile Zoom'
              name: 'zoom'
              widget: 'number'
              value_type: 'float'
              step: 0.01
              required: false
              collapsed: true
        - label: 'Captions'
          name: 'captions'
          widget: 'object'
          required: false
          collapsed: true
          default: null
          fields:
            - label: 'Title'
              name: 'title'
              widget: 'string'
              required: false
              collapsed: true
            - label: 'Notes'
              name: 'notes'
              widget: 'string'
              required: false
              collapsed: true
            - label: 'Items'
              name: 'items'
              widget: 'list'
              required: false
              collapsed: true
              fields:
                - label: 'Icon'
                  name: 'icon'
                  widget: 'string'
                  required: false
                  collapsed: true
                - label: 'Text'
                  name: 'text'
                  widget: 'string'
                  required: false
                  collapsed: true
    - label: 'Map View'
      name: 'mapView'
      widget: 'string'
      required: false
      collapsed: true
