mapView: &mapView
  label: 'Map View'
  name: 'MapView'
  widget: 'object'
  summary: '{{fields.mapView}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'MapView'
      collapsed: true
    - label: 'Map View'
      name: 'mapView'
      widget: 'string'
      required: true
      hint: 'Digite o ID da view do mapa (ex: view_0, view_12, etc.) - deve corresponder a uma view cadastrada no mapbox'
      collapsed: true
    - label: 'Text Color'
      name: 'txtColor'
      widget: 'color'
      required: false
      enableAlpha: true
      allowInput: true
      collapsed: true
    - label: 'Background Color'
      name: 'bgColor'
      widget: 'color'
      required: false
      enableAlpha: true
      allowInput: true
      collapsed: true
