pageSettings: &pageSettings
  label: 'Page Settings'
  name: 'pageSettings'
  collapsed: true
  widget: 'object'
  fields:
    - label: 'Language'
      name: 'language'
      widget: 'select'
      options: ['pt-BR', 'en', 'es']
      default: 'pt-BR'
      collapsed: true
    - label: 'Link pt-br'
      name: 'link_pt_br'
      widget: 'string'
      required: false
      default: '#'
      collapsed: true
    - label: 'Link en'
      name: 'link_en'
      widget: 'string'
      required: false
      default: '#'
      collapsed: true
    - label: 'Link es'
      name: 'link_es'
      widget: 'string'
      required: false
      default: '#'
      collapsed: true
    - label: 'Animations'
      name: 'animations'
      widget: 'select'
      options: 
        - { label: 'Enable All', value: 'enable_all' }
        - { label: 'Disable All', value: 'disable_all' }
        - { label: 'Custom by Components', value: 'custom' }
      default: 'enable_all'
      required: true
      hint: 'Control animation behavior for the entire page'
      collapsed: true
    - label: 'Text Direction'
      name: 'direction'
      widget: 'select'
      options: ['left', 'right']
      default: 'left'
      collapsed: true
    - label: 'SEO Title'
      name: 'seoTitle'
      widget: 'string'
      required: false
      collapsed: true
    - label: 'SEO Description'
      name: 'seoDescription'
      widget: 'string'
      required: false
      collapsed: true
    - label: 'SEO Keywords'
      name: 'seoKeywords'
      widget: 'list'
      required: false
      collapsed: true
      fields:
        - { label: 'Keyword', name: 'keyword', widget: 'string', collapsed: true }
    - label: 'SEO Image'
      name: 'seoImage'
      widget: 'image'
      required: false
      collapsed: true
