text: &text
  label: 'Text'
  name: 'Text'
  widget: 'object'
  summary: '{{fields.content}}'
  collapsed: true
  fields:
    - label: 'Dropcap'
      name: 'hasDropCap'
      widget: 'boolean'
      required: false
      collapsed: true
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Text'
      collapsed: true
    - label: 'Content'
      name: 'content'
      widget: 'markdown'
      required: false
      collapsed: true
