timeline: &timeline
  label: 'Timeline'
  name: 'Timeline'
  widget: 'object'
  summary: 'Timeline'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'Timeline'
    - label: 'Components'
      name: 'components'
      widget: 'list'
      required: false
      types:
        - *timelineBullet
