timelineBullet: &timelineBullet
  label: 'Timeline Bullet'
  name: 'TimelineBullet'
  widget: 'object'
  summary: '{{fields.text}}'
  collapsed: true
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'TimelineBullet'
      collapsed: true
    - label: 'Text'
      name: 'text'
      widget: 'string'
      required: false
      collapsed: true
    - label: 'Content'
      name: 'content'
      widget: 'markdown'
      required: false
      collapsed: true
