videoEmbed: &videoEmbed
  label: 'Video Embed'
  name: 'VideoEmbed'
  widget: 'object'
  summary: '{{fields.videoUrl}}'
  fields:
    - label: 'Type'
      name: 'type'
      widget: 'hidden'
      default: 'VideoEmbed'
    - label: 'Wide'
      name: 'wideVideo'
      widget: 'boolean'
      required: false
      default: false
    - label: 'Video URL'
      name: 'videoUrl'
      widget: 'string'
      required: false
    - label: 'Video Caption'
      name: 'videoCaption'
      widget: 'string'
      required: false
